-- AlterTable
ALTER TABLE "site_settings" ADD COLUMN     "community_instagram_enabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "community_instagram_subtitle" TEXT,
ADD COLUMN     "community_instagram_title" TEXT,
ADD COLUMN     "facebook_url" TEXT,
ADD COLUMN     "footer_description" TEXT,
ADD COLUMN     "footer_show_socials" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "instagram_handle" TEXT,
ADD COLUMN     "newsletter_button_text" TEXT,
ADD COLUMN     "newsletter_description" TEXT,
ADD COLUMN     "newsletter_enabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "newsletter_eyebrow" TEXT,
ADD COLUMN     "newsletter_placeholder" TEXT,
ADD COLUMN     "newsletter_success_message" TEXT,
ADD COLUMN     "newsletter_title" TEXT,
ADD COLUMN     "tiktok_url" TEXT,
ADD COLUMN     "trust_block_enabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "trust_items_json" JSONB,
ADD COLUMN     "youtube_channel_label" TEXT,
ADD COLUMN     "youtube_channel_url" TEXT,
ADD COLUMN     "youtube_handle" TEXT,
ADD COLUMN     "youtube_section_enabled" BOOLEAN NOT NULL DEFAULT true,
ADD COLUMN     "youtube_section_subtitle" TEXT,
ADD COLUMN     "youtube_section_title" TEXT,
ADD COLUMN     "youtube_url" TEXT,
ADD COLUMN     "youtube_videos_json" JSONB;
